version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "9000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "9001:5000"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DB= ALLTrees
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ALLTrees
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql