import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const AuthPage = () =>{
    return(

        <div className={styles.fondoNormal}>
              <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <section className={styles.specialRectangle}>
                <h4>To run queries and access other's queries you need log in with your email and username. If you dont have an account you can input your email and create an username:</h4>
                <form className={styles.formulary}>
                 <label>Email: </label> 
                 <input className={styles.input} type={"email"} id={"email"} placeholder={"youremail@example.com"}></input> 
                 <label>Username:</label> 
                 <input className={styles.input}  id={"username"} placeholder={"anAwesomeUser"}></input> 
                </form>
                <button className={styles.rectangularButton}>
                    <a href='./queryRun'><p>Continue LogIn</p></a>
                </button>
            </section>
        </div>
    );

}

export default AuthPage