import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      <main className={styles.main}>
      <Head>
        <title>All about trees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section className={styles.defaultRectangle}>
          <div className={styles.flexRow}>
            <h1>Everything About Trees 🌳</h1>
            <h3>Millions of trees, just in one place</h3>
          </div>
          <div className={styles.flexRow}>
           
           <button className={styles.regularButton}><a href='./auth'>Start now</a> </button>
            
            </div>
          <p>Image from <a href='https://giphy.com/gifs/forest-fall-79t3s6YcsADCg' target="_blank"> giphy</a></p>
        </section>
      </main>
  )
}

export default Home
