import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar';
import ProfileDiv from '../components/profileDiv';
import QueryInfo from '../components/queryInfo';
import { useEffect, useRef, useState } from 'react'
import { useUser } from './context/UserContext';
import {useQuery} from './context/QueryContext';
import Loading from '../components/loading';

const Profile = () =>{
    const [queries,setQ] = useState<any[]>([])  
    const {username,setLoggedInUser} = useUser();
    const {queryId,setQueryId} = useQuery();
    function getPageData() {
        let apiUrlEndpoint = "../api/user/queries/"+username;
          fetch(apiUrlEndpoint)
          .then(response => response.json())
          .then(res => {
            if (res !== undefined) {
              setQ(res.result);
              console.log(queries)
            }
          })
          .catch(error => {
            console.error('Error fetching data:', error);
            // Manejar el error según sea necesario
          });

  
      }


  
      useEffect(
           ()=>{ getPageData()
          },[]
      );


    return(
        <div className={styles.fondoNormal}>
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar></NavBar>
        <div className={styles.flexColumn}>
            <section className={styles.flexRow}>
                <ProfileDiv {...["My profile",username]}></ProfileDiv>
                <ProfileDiv {...["Saved Queries",queries.length]}></ProfileDiv>
            </section>
            <div className={styles.specialRectangle}>
                <button className={styles.rectangularButton} onClick={getPageData}><h3>Refresh</h3></button>
                {queries.length === 0?
                 <p>It seems that you haven't saved any queries. You can go to search queries to give yourself some ideas</p>:
                 (queries.map((q)=>(
                 <a href="./queryRun" onClick={()=>{
                  setQueryId(q[0])
                 }}><QueryInfo {...q} ></QueryInfo></a>
                 )))}
            </div>
            
            
        </div>
        </div>
    );
}

export default Profile;