import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar';
import InfoDiv from '../components/infoDiv';
import QueryBuilder from '../components/queryBuilder';
import Comment from '../components/comment';
import PostComment from '../components/postComment';


const QueryRun = () => {

  const comments:string[][] = [['user1','wow'],['user2','such incredible query'],['user3','amazing, super interesting'],['user4','i would like to collaborate with you']]
  return (
    <div className={styles.fondoNormal}>
      <Head>
        <title>Query UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <InfoDiv {...["¿How it works?", "Create your query with our visual-query builder. Our app will fetch the data from the USFS FIA database hosted on google cloud platform."]}></InfoDiv>
      <QueryBuilder></QueryBuilder>
      <section className={styles.flexRow}>
        <article className={styles.graphsContainer}>Hola</article>
        <div className={styles.commentsColumn}>
          <h3>Query's information</h3>
          <InfoDiv{...["Author", "Username"]}></InfoDiv>
          <button className={styles.regularButton}>Save this query</button>
          <section className={styles.commentSection}>
            {comments.map((comment)=>(<Comment {...comment}></Comment>))}
            <PostComment {...["user"]}></PostComment>
          </section>

        </div>
      </section>
    </div>

  );

}

export default QueryRun