import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar';
import QueryInfo from '../components/queryInfo';
import { useRef } from 'react';

const QuerySearch = () =>{
    const inputQuery = useRef<HTMLInputElement>(null);
    const queries = [["Such amazing query","this query is for bla bla bla bla","Author's name"],["Such amazing query","this query is for bla bla bla bla","Author's name"]];

    return (
        <div className={styles.fondoNormal}>
        <Head>
          <title>Query Search</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar></NavBar>
        <div className={styles.flexColumn}>
            <section className={styles.flexRowGreen}>
                <div className={styles.flexColumnG}>
                    <h2>Search Prexisting queries</h2>
                    <input className={styles.qinput} type={"text"} ref={inputQuery} ></input>
                </div>
                <div className={styles.flexColumnG}>
                    <button className={styles.regularButton}>Search by name</button>
                    <button className={styles.regularButton}>Search by autor</button>
                </div>

            </section>
            <div className={styles.specialRectangle}>
                {queries.map((q)=>(<QueryInfo {...q}></QueryInfo>))}
            </div>
            
            
        </div>
        </div>
    );
}

export default QuerySearch;