import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar';
import InfoDiv from '../components/infoDiv';
import QueryBuilder from '../components/queryBuilder';


const QueryRun = () =>{
    return(  
        <div className={styles.fondoNormal}>
              <Head>
        <title>Query UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
           <InfoDiv {...["¿How it works?","Create your query with our visual-query builder. Our app will fetch the data from the USFS FIA database hosted on google cloud platform."]}></InfoDiv>
            <QueryBuilder></QueryBuilder>
           <section className={styles.flexRow}>
        <article>Hola</article>
      </section>
        </div>
      
    );

}

export default QueryRun